model_config:
  target: src.geolrm_wrapper.GeoLRM
  params:
    init_ckpt: ckpts/geolrm.ckpt
    serializer_config:
      target: src.serializers.geo_srl.TransformerSerializer
      params:
        use_bf16: false
        encoder_freeze: false
        encoder_model_name: facebook/dinov2-base
        encoder_feat_dim: 384
        transformer_dim: 384
        transformer_layers: 6
        transformer_heads: 16
        grid_size: 128
        token_res: 8
        num_deform_points: 8
        max_seq_len: 8192
        ckpt_path:
    lrm_generator_config:
      target: src.models.geolrm.GeoLRM
      params:
        use_bf16: false
        encoder_feat_dim: 384
        encoder_freeze: false
        encoder_model_name: facebook/dinov2-base
        transformer_dim: 768
        transformer_layers: 16
        transformer_heads: 16
        grid_size: 128
        num_deform_points: 8
        gs_per_token: 32
        use_sh: false
        dropout: 0.0
        offset_max: 0.2
        scale_max: 0.02

infer_config:
  render_resolution: 1024
